services:
  web:
    build: .
    image: mgrecuccio/bookstore
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-woiwj7btwn=$^a26bp7cq(j-yj0e@7(xq93m@389xg)3r3t3e1"
      - "DJANGO_DEBUG=True"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: